### ISSUE TITLE
Portable .yml syntax between drill and blazemeter

### ISSUE THREAD

**Issue by jrabello** [fcsonline/drill#65]
Hi, thanks for creating drill, very interesting tool

I'd like to know if there is some kind of way to convert drill .yml to blazemeter .yml which looks very similar, but I believe it's not compatible

Can you help me to create some kind of converter? 
There is some kind of parser available for ansible syntax?

Thanks!!!

**Comment by fcsonline** [comment]
You can check all the files in `./examples` and review the [syntax](https://github.com/fcsonline/drill/blob/master/SYNTAX.md) file to understand the structure of the yaml file. I would not include converters in this project because there are many solutions out there, but if you want to code the converter, go ahead! :ok_hand:

**Comment by jrabello** [comment]
that's ok thanks :+1:
